services:
  server:
    platform: linux/amd64
    build: ./server
    container_name: api_backend
    ports:
      - "8080:8080"
    volumes:
      - ./server:/src
      - /server/node_modules
    working_dir: /src
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/src
      - /src/node_modules
    working_dir: /src
    environment:
      - NODE_ENV=development
