services:
  api:
    build: ./server
    container_name: api_backend
    ports:
      - "8080:8080"
    volumes:
      - ./server:/server
      - /server/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/src
      - /src/node_modules
    working_dir: /src
    command: sh -c "npm install && npm run dev"
